// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCI03-2-zQXHEaIXMyNEaq_8jhjPZdqx4',
    appId: '1:558363209301:web:5c055839ac997665426edc',
    messagingSenderId: '558363209301',
    projectId: 'dreamloop-f1bc9',
    authDomain: 'dreamloop-f1bc9.firebaseapp.com',
    storageBucket: 'dreamloop-f1bc9.firebasestorage.app',
    measurementId: 'G-P4EX5CL90T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbDnJ32Uqs1GmMAdQH-3-KiaKZh4B7HDA',
    appId: '1:558363209301:android:a3d1b56b540794b5426edc',
    messagingSenderId: '558363209301',
    projectId: 'dreamloop-f1bc9',
    storageBucket: 'dreamloop-f1bc9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVYiu5PKTakaILi4alT5BapxXYbiJDpvk',
    appId: '1:558363209301:ios:48e6756ff696397c426edc',
    messagingSenderId: '558363209301',
    projectId: 'dreamloop-f1bc9',
    storageBucket: 'dreamloop-f1bc9.firebasestorage.app',
    iosBundleId: 'com.dreamloop.dreamloop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVYiu5PKTakaILi4alT5BapxXYbiJDpvk',
    appId: '1:558363209301:ios:b2c1389bb9b47adb426edc',
    messagingSenderId: '558363209301',
    projectId: 'dreamloop-f1bc9',
    storageBucket: 'dreamloop-f1bc9.firebasestorage.app',
    iosBundleId: 'com.example.dreamloop',
  );
}
